### ISSUE TITLE
Production usage?

### ISSUE THREAD

**Issue by Kadeluxe** [electrode-io/fyn#13]
Hey!
Discovered this accidentally using Github search. 
I was looking for something related to 'better' linking of packages and seems like `fynlocal` is very close to what I was going to do on my own.

I haven't found any notable mentions of `fyn` online. 
What is the state of this project? 
I see it is under electrode org and I guess you use it for your own needs in-house. 
So do you think it is a viable alternative to pnpm?

**Comment by jchip** [comment]
we've used this exclusively for a few years now, works quite well for our needs.  We are also using it to keep our lerna based mono-repo projects.  any issue or feature requests, I'd be happy to consider them.

**Comment by jchip** [comment]
our open sourced project https://github.com/electrode-io/electrode started as a lerna based mono-repo, but we've modified it to used fyn exclusively for dep install and local linking.

fyn auto detects packages that are local to the mono-repo and link them with standard npm install techniques, no funny symlinking, hoisting etc that other workspace solution use.  If your package breaks when you publish them, they will break in your mono-repo also.

Internally, we have a few big projects (with 30-50 modules) using the same setup.

**Comment by Kadeluxe** [comment]
Alright, I will look into it.
Thanks 👍
